services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/db
      - media-data:/app/media
      - logs-data:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    command: python dream_recorder.py
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db-data:
  media-data:
  logs-data: